### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by FrancescElies** [jmcarp/flask-apispec#27]
Hi,
I could read the following in the README file.

> flask-apispec isn't stable yet, and the interface and internals may change. Bug reports and pull requests are much appreciated.

Is this still the case? 
Thanks in advance for your response

**Comment by rth** [comment]
@FrancescElies Well I think that sentence applies to most open-source projects. Stability is subjective and interface / internals always evolve. Personally I'm using this for a project in production and haven't seen any issues so far. There isn't a lot of development happening at the moment and because this project has been around for some time, I imagine as users could expect that future changes won't break backward compatibility too badly.

Not sure if that answers your question...

**Comment by FrancescElies** [comment]
This answers my question , thank you for your reply :)
